export const countries = [
    "Abu Dhabi", "Albania", "Algeria", "Andorra (Principality of)", "Angola",
    "Anguilla", "Antigua & Barbuda", "Argentina", "Armenia", "Aruba",
    "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "British Virgin Islands",
    "Brunei", "Bulgaria", "Burkina Faso", "Cambodia", "Cameroon", "Canada",
    "Cape Verde", "Cayman Islands", "Channel Islands", "Chile", "China",
    "Colombia", "Congo (Democratic Republic)", "Congo (Republic of)", "Cook Islands",
    "Costa Rica", "Croatia", "Cuba", "Curaçao", "Cyprus", "Czech Republic",
    "Denmark", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
    "Estonia", "Ethiopia", "Falkland Islands", "Fiji", "Finland", "France",
    "French Guiana", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
    "Gibraltar", "Greece", "Greenland", "Guatemala", "Guernsey (States of)",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong",
    "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Isle of Man", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan",
    "Jersey (States of)", "Jordan", "Kazakhstan", "Kenya", "Korea, D.P.R.",
    "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Liberia", "Libya",
    "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar",
    "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Martinique", "Mauritius",
    "Mexico", "Monaco", "Moldova", "Mongolia", "Montenegro", "Montserrat",
    "Morocco", "Mozambique", "Myanmar", "Namibia", "Netherlands",
    "Netherlands Antilles", "New Zealand", "Nicaragua", "Niger", "Nigeria",
    "Norway", "Oman", "Pakistan", "Palestinian Authority", "Panama",
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
    "Qatar", "Ras Al Khaimah (Emirate of)", "Reunion", "Romania", "Russia",
    "Rwanda", "Saint Lucia", "Saudi Arabia", "Senegal", "Serbia", "Sharjah",
    "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
    "Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "St. Maarten",
    "St. Vincent & the Grenadines", "Sudan", "Suriname", "Swaziland", "Sweden",
    "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
    "Togo", "Trinidad & Tobago", "Tunisia", "Turkey", "Turks & Caicos Islands",
    "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
    "United States", "Uruguay", "Uzbekistan", "Venezuela", "Vietnam", "Yemen",
    "Zambia", "Zimbabwe"
];

export const industries = [
    "Advertising",
    "Aerospace/Defense",
    "Air Transport",
    "Apparel",
    "Auto & Truck",
    "Auto Parts",
    "Bank (Money Center)",
    "Banks (Regional)",
    "Beverage (Alcoholic)",
    "Beverage (Soft)",
    "Broadcasting",
    "Brokerage & Investment Banking",
    "Building Materials",
    "Business & Consumer Services",
    "Cable TV",
    "Chemical (Basic)",
    "Chemical (Diversified)",
    "Chemical (Specialty)",
    "Coal & Related Energy",
    "Computer Services",
    "Computers/Peripherals",
    "Construction Supplies",
    "Diversified",
    "Drugs (Biotechnology)",
    "Drugs (Pharmaceutical)",
    "Education",
    "Electrical Equipment",
    "Electronics (Consumer & Office)",
    "Electronics (General)",
    "Engineering/Construction",
    "Entertainment",
    "Environmental & Waste Services",
    "Farming/Agriculture",
    "Financial Svcs. (Non-bank & Insurance)",
    "Food Processing",
    "Food Wholesalers",
    "Furn/Home Furnishings",
    "Green & Renewable Energy",
    "Healthcare Products",
    "Healthcare Support Services",
    "Heathcare Information and Technology",
    "Homebuilding",
    "Hospitals/Healthcare Facilities",
    "Hotel/Gaming",
    "Household Products",
    "Information Services",
    "Insurance (General)",
    "Insurance (Life)",
    "Insurance (Prop/Cas.)",
    "Investments & Asset Management",
    "Machinery",
    "Metals & Mining",
    "Office Equipment & Services",
    "Oil/Gas (Integrated)",
    "Oil/Gas (Production and Exploration)",
    "Oil/Gas Distribution",
    "Oilfield Svcs/Equip.",
    "Packaging & Container",
    "Paper/Forest Products",
    "Power",
    "Precious Metals",
    "Publishing & Newspapers",
    "R.E.I.T.",
    "Real Estate (Development)",
    "Real Estate (General/Diversified)",
    "Real Estate (Operations & Services)",
    "Recreation",
    "Reinsurance",
    "Restaurant/Dining",
    "Retail (Automotive)",
    "Retail (Building Supply)",
    "Retail (Distributors)",
    "Retail (General)",
    "Retail (Grocery and Food)",
    "Retail (REITs)",
    "Retail (Special Lines)",
    "Rubber & Tires",
    "Semiconductor",
    "Semiconductor Equip",
    "Shipbuilding & Marine",
    "Shoe",
    "Software (Entertainment)",
    "Software (Internet)",
    "Software (System & Application)",
    "Steel",
    "Telecom (Wireless)",
    "Telecom. Equipment",
    "Telecom. Services",
    "Tobacco",
    "Transportation",
    "Transportation (Railroads)",
    "Trucking",
    "Utility (General)",
    "Utility (Water)",
    "Total Market",
    "Total Market (without financials)"
];


export const syntheticRatings = [
    "D2/D",
    "C2/C",
    "Ca2/CC",
    "Caa/CCC",
    "B3/B-",
    "B2/B",
    "B1/B+",
    "Ba2/BB",
    "Ba1/BB+",
    "Baa2/BBB",
    "A3/A-",
    "A2/A",
    "A1/A+",
    "Aa2/AA",
    "Aaa/AAA"
];