export const FUNDAMENTAL_DEFINITIONS: Record<string, string> = {
    // Income Statement Fields
    "Total Revenue": "The total amount of money generated from the sale of goods or services in a company's primary operations.",
    "Reconciled Cost Of Revenue": "The direct costs incurred to produce or acquire the goods and services a company sells, such as raw materials or production labor. These are typically variable costs that change with sales volume.",
    "Gross Profit": "Revenue minus cost of revenue.",
    "Selling General And Administration": "Selling, general and administrative (SG&A) is an operating expense. It involves various company expenses that are not related to production, such as salaries and advertising.",
    "Research And Development": "Research and development (R&D) is an operating expense. It is the amount of money a company spends on researching and developing new products and services, or improving existing ones.",
    "Reconciled Depreciation": "Depreciation: The gradual expense of a tangible asset’s cost over its useful life (e.g., equipment, buildings).\nAmortization: The gradual expense of an intangible asset’s cost over its useful life (e.g., patents, software).",
    "Operating Income": "Operating income is the amount of profit a company has after paying for all the expenses related to its core operations.\nOperating Income = Revenue - Cost of Revenue - Operating Expenses\nFor FCFF calculate we Yahoo Finance's Operating Income but named it EBIT",
    "EBIT": "EBIT stands for 'Earnings Before Interest and Taxes' and is a commonly used measure of earnings or profits. It is similar to operating income.\nEBIT = Net Income + Interest + Taxes",
    "Operating Margin": "The ratio of operating income to total revenue, expressed as a percentage.",
    "Interest Income": "Income earned from interest on investments or cash holdings.",
    "Interest Expense": "The cost of borrowed funds paid to lenders.",
    "Other Income Expense": "Expenses from non-operating activities.",
    "Other Non Operating Income Expenses": "Non-operating income or expenses not related to interest.",
    "Pretax Income": "Earnings before income taxes, combining operating and non-operating income.",
    "Tax Provision": "The expense recorded for income taxes payable.",
    "Net Income": "The company's total profit after all expenses, including taxes, are deducted from revenue.",
    "Basic EPS": "Earnings Per Share, calculated as net income divided by the number of outstanding shares.",
    "Diluted EPS": "Earnings Per Share adjusted for potential dilution from convertible securities or stock options.",

    // Balance Sheet Fields
    "Current Assets": "Assets expected to be converted into cash or used up within one year.",
    "Cash And Cash Equivalents": "Highly liquid assets, including cash and short-term investments with maturities of 90 days or less.",
    "Restricted Cash": "Cash set aside for specific purposes and not available for general use.",
    "Other Short Term Investments": "Short-term investments are liquid assets like treasury bills, short-term bonds, money-market funds, marketable securities and other investments that can be sold for cash at a short notice.",
    "Cash Cash Equivalents And Short Term Investments": "The total of cash, cash equivalents, and other short-term investments.",
    "Receivables": "The total amount owed to the company by customers and others.",
    "Accounts Receivable": "Money owed by customers for goods or services sold on credit.",
    "Taxes Receivable": "Tax refunds or credits owed to the company.",
    "Other Receivables": "Miscellaneous amounts owed to the company not classified as accounts or taxes receivable.",
    "Inventory": "Goods held for sale or use in production.",
    "Prepaid Expenses": "Payments made in advance for goods or services to be received within a year.",
    "Current Deferred Assets": "Assets related to deferred costs or revenues expected to benefit the current period.",
    "Other Current Assets": "Miscellaneous assets expected to be converted to cash within one year.",
    "Total Non Current Assets": "Assets not expected to be converted into cash within one year.",
    "Net PPE": "Property, Plant, and Equipment, net of accumulated depreciation.",
    "Goodwill": "The excess of purchase price over the fair value of net assets acquired in a business combination.",
    "Other Intangible Assets": "Non-physical assets like patents or trademarks, excluding goodwill.",
    "Goodwill And Other Intangible Assets": "The combined value of goodwill and other intangible assets.",
    "Long Term Equity Investment": "Investments in equity securities held for more than one year.",
    "Investmentin Financial Assets": "Long-term investments in financial instruments.",
    "Investments And Advances": "Total investments and loans made to other entities.",
    "Non Current Deferred Taxes Assets": "Tax benefits expected to be realized beyond one year.",
    "Non Current Prepaid Assets": "Prepaid expenses extending beyond one year.",
    "Other Non Current Assets": "Miscellaneous assets not expected to be liquidated within a year.",
    "Total Assets": "The sum of all current and non-current assets owned by the company.",
    "Current Liabilities": "Obligations due within one year.",
    "Current Debt": "Debt obligations, including loans and notes, due within one year.",
    "Current Capital Lease Obligation": "Lease payments due within one year under capital lease agreements.",
    "Accounts Payable": "Amounts owed to suppliers for goods or services purchased on credit.",
    "Current Deferred Revenue": "Revenue received in advance for goods or services to be delivered within a year.",
    "Income Tax Payable": "Taxes owed to the government due within one year.",
    "Other Current Liabilities": "Miscellaneous obligations due within one year.",
    "Total Non Current Liabilities Net Minority Interest": "Liabilities due after one year, excluding minority interest.",
    "Long Term Debt": "Debt obligations due beyond one year.",
    "Long Term Capital Lease Obligation": "Lease payments due beyond one year under capital leases.",
    "Non Current Deferred Revenue": "Revenue received in advance for goods or services to be delivered beyond one year.",
    "Non Current Deferred Taxes Liabilities": "Tax obligations deferred beyond one year.",
    "Non Current Deferred Liabilities": "Other deferred obligations due after one year.",
    "Other Non Current Liabilities": "Miscellaneous liabilities due beyond one year.",
    "Total Liabilities Net Minority Interest": "The sum of all current and non-current liabilities, excluding minority interest.",
    "Total Equity Gross Minority Interest": "The total equity before subtracting minority interest.",
    "Common Stock": "The par value of issued common shares.",
    "Additional Paid In Capital": "The amount paid by investors above the par value of shares.",
    "Retained Earnings": "Accumulated profits retained by the company after dividends.",
    "Gains Losses Not Affecting Retained Earnings": "Unrealized gains or losses from items like foreign currency translation.",
    "Stockholders Equity": "Stockholders equity is also called book value or net worth. It can be seen as the amount of money held by investors inside the company. It is calculated by subtracting all liabilities from all assets.\nShareholders' Equity = Total Assets - Total Liabilities",
    "Minority Interest": "The portion of equity in subsidiaries not owned by the parent company.",
    "Total Debt": "The sum of all short-term and long-term debt obligations.",
    "Net Debt": "Total debt minus cash and cash equivalents."
};