export const PRESENT_VALUE_OF_FREE_CASH_FLOW = {
    "Revenue": {
        definition: "The total income generated from sales of goods or services before any costs or expenses are deducted.",
    },
    "EBIT Margin": {
        definition: `The percentage of revenue that remains as operating profit before interest and taxes, measuring operational efficiency.
        
        The model forecasts EBIT margins by linearly converging from the initial year's margin to a target margin over a specified time period. For years beyond the convergence period, the margin remains at the final target value.
        
        It essentially measures a company's ability to generate profit from its primary business activities, isolating the impact of its operational decisions, pricing strategy, and cost management, without being influenced by how it's financed(where the company lend its money) or its tax structure.
        `,

        formula: "EBIT Margin = EBIT / Revenue",
    },
    "EBIT": {
        definition: "Earnings Before Interest and Taxes, a measure of a company's operating profitability without considering capital structure or tax implications.",
        formula: "EBIT = Revenue × EBIT Margin",
    },
    "Tax Rate": {
        definition: "A series of projected tax rates used to calculate after-tax cash flows. It typically starts with the current effective tax rate and linearly converges towards the long-term marginal tax rate.",
        formula: "Base Year - Year 5: Effective Tax Rate. Years 6 - 10: Linear interpolation from the Effective Tax Rate to the Marginal Tax Rate. Terminal Year: Marginal Tax Rate.",
    },
    "EBIT After Tax": {
        definition: "Earnings Before Interest and Taxes, if the current year EBIT is 0 and below there wouldn't be any taxes applied",
        formula: "EBIT After Tax = EBIT × (1 - Tax Rate)",
    },
    "Reinvestment": {
        definition: `The capital expenditures and working capital investments required by the company to support its projected future revenue growth.
        
        **Historical/Current Period Calculation**
        Reinvestment = Acquisitions + Capital Expenditures (net of depreciation) + Change in Working Capital

       **DCF Forecasting Approach**
        For the explicit forecast period (Years 1-10), reinvestment is driven by the expected change in revenue relative to the sales-to-capital ratio.

    For the terminal year, reinvestment is calculated based on the principle of sustainable growth. It represents the portion of EBIT After Tax (NOPAT) that must be reinvested to sustain the company's assumed long-term, stable growth rate, given its Return on Invested Capital (ROIC). This formula ensures that in perpetuity, growth is precisely matched by the necessary reinvestment to maintain that growth, considering the efficiency of capital deployment.
    
    **Why Damodaran use Sales to Capital Ratio as a proxy**
    __Simplification of Forecasting__: Instead of separately projecting capital expenditures, working capital changes, and acquisitions (which can be highly variable), the Sales to Capital ratio provides a more stable metric for forecasting.

    `,

        formula: `Years 1-10: (Current Year Revenue - Previous Year Revenue) / Sales to Capital Ratio
    Terminal Year: EBIT After Tax (Terminal Year) × (Terminal Revenue Growth Rate / Terminal ROIC)`,
    },
    "Free Cash Flow to Firm": {
        definition: `Cash flow available to all providers of capital (both debt and equity) after accounting for operating expenses, taxes, and reinvestment needs
        
        FCFF is simply the cash that's left over after the company has taken care of all its operating needs and invested for the future. It's the total pool of cash generated by the business itself that is available to all the people who provided capital (__debt and share holders__).
        
        Unlike Net Income, which is an accounting measure that includes non-cash items (like depreciation) and is affected by the company's capital structure (due to interest expense), FCFF provides a view of the company's unlevered cash flow – the cash flow it would generate if it had no debt.

        **Formula from Net Income (Historical)**:
        FCFF = Net Income + Non-cash Charges + Interest Expense × (1 − Tax Rate) − Capital Expenditures− Change in Net Working Capital
         
        1. Start with Net Income: 
        This is the profit after all expenses, including interest and taxes. But remember, this isn't pure cash, and it's already accounted for debt interest.
        2. + Non-Cash Expenses (like Depreciation & Amortization): 
        These reduced Net Income but didn't use cash. Since we want to see the actual cash generated, we add these back.
        3. + Interest Expense (Adjusted for Taxes):
         Net Income was calculated after paying interest (e.g company take loan). But FCFF is the cash available before paying debt holders. So, we need to add back the interest payments.
        4. - Capital Expenditures (CapEx): 
        This is the cash the company spent on long-term assets (like machinery, buildings). This cash is used to maintain and grow the business's ability to operate in the future and is not available to capital providers. So, we subtract it.
        5. - Change in Net Working Capital (NWC): 
        This accounts for the cash tied up or released in the short-term operations.
`,
        formula: "FCFF = EBIT × (1 - Tax Rate) - Reinvestment",
    },
    "Weighted Average Cost of Capital": {
        definition: `The average rate a company expects to pay to finance its assets, weighted by the proportion of debt and equity in its capital structure. It represents the minimum return required by all investors (both debt and equity holders).

    In this model, the WACC is assumed to be constant at an initial rate for the first five years, then linearly converges to a long-term terminal WACC over the subsequent five years. From Year 11 onwards, it remains at the terminal WACC.`,
        formula: `Initial WACC = (Market Value of Equity / (Market Value of Equity + Market Value of Debt)) × Cost of Equity + (Market Value of Debt / (Market Value of Equity + Market Value of Debt)) × Cost of Debt × (1 - Tax Rate)

    Base Year - Year 5: Initial WACC
    Years 6-10: Linear interpolation from Initial WACC to Terminal WACC. The WACC for each year is calculated by subtracting a fixed decrement (Initial WACC - Terminal WACC) / 5 from the previous year's WACC.
    Terminal Year: Terminal WACC`,
    },
    "Cumulated Discount Factor": {
        definition: "A factor used to discount future cash flows to present value, accounting for compounding over multiple periods.",
        formula: "Cumulated Discount Factor = 1 / (1 + WACC)^n where n is the number of periods",
    },
    "Present Value of FCFF": {
        definition: "The current value of future Free Cash Flow to Firm, discounted using the Weighted Average Cost of Capital to account for the time value of money.",
        formula: "PV of FCFF = FCFF × Cumulated Discount Factor",
    }
};


export const COMPANY_ANALYSIS = {
    "Understand the business model": {
        definition: ` How does [ticker] generate revenue today? Provide a breakdown of its key products, services, and pricing models, including the percentage contribution of each revenue stream.

What are [ticker]’s potential future revenue streams or strategic initiatives? Include details on planned product launches, market expansions, or innovation strategies. 

How cyclical is [ticker]’s business? Specify whether it is affected by economic cycles, seasonal patterns, or external factors (e.g., interest rates, commodity prices, regulations), and explain the impact on revenue and profitability.

Can you provide a detailed list of publicly traded companies comparable to [the stock]? Please include their ticker symbols, market segments, and a brief explanation of why each company is considered a comparable—focusing on similarities in business model, size, growth rates, and market dynamics.?

Using Aswath Damodaran's methodology for defining corporate life cycle stages, can you analyze [the stock] and determine which phase it is currently in? Please categorize it according to his framework—for example, as a startup/early-stage, high growth, mature growth, mature stable, or decline phase. In your analysis, incorporate key performance indicators such as revenue growth, operating margin, reinvestment, sales to capital ratio. 
`
    },
    "Evaluate Management Quality": {
        definition: `Has management consistently delivered ROIC above the cost of capital over multiple years?

How does the company's ROIC compare to industry peers?

How has [ticker]’s management allocated capital across organic growth, acquisitions, dividends, and share repurchases? Quantify the allocation (e.g., R&D spend, buyback amounts) and assess its effectiveness.- Have past acquisitions created or destroyed shareholder value?

Have [ticker]’s past acquisitions created or destroyed shareholder value? Provide examples, including metrics like goodwill impairments or post-acquisition revenue growth, and evaluate integration success.?
Is [ticker]’s dividend policy sustainable and appropriate for its life cycle stage? Include payout ratio, dividend yield, and cash flow coverage.

Is there a gap between [ticker]’s management’s promises (e.g., guidance, strategic goals) and actual performance? Provide specific examples of met or missed targets.
`
    },
    "Identify Growth Drivers": {
        definition: `What is [ticker]’s total addressable market (TAM) and current market penetration? Quantify the potential for market share growth.
        
What is [ticker]’s product or service development pipeline? Highlight specific upcoming products, services, or innovations and their expected revenue impact.
        
Is the industry it is in growing, mature, or declining? At what rate?

Is there any Geographic expansion opportunities

Is there any Industry tailwinds or headwinds

What is the Pricing power and scalability
`
    }
}

export const CORPORATE_LIFECYCLE = {
    "1. Start Up (The Lightbulb Moment)": {
        definition: `💡 **Key Focus**: Turning an idea into a product or service.
  
  🔴 **Key Risk**: Failure in product development or finding market fit.
  
  **Revenue Growth**: Very High Potential but Pre-Revenue – Most companies don't generate revenue yet, or if they do, it's minimal.
  **Operating margin**: Very Negative ~ Very Low - Heavy R&D and marketing expenses
  **Reinvestment**: High - spending on R&D, product development, hiring, technology and infrastructure
  **Sales to Capital Ratio**: Very Low - With minimal or no sales(revenue) and significant capital invested, the ratio of sales to capital is very small`,
    },

    "2. Young Growth (The Product Test)": {
        definition: `💡 **Key Focus**: Developing a business model and converting ideas into revenue.
  
  🟠 **Key Risk**: Failure in creating a scalable business model.
  
  **Revenue Growth**: Very High - Early adopters start using the product, and sales begin ramping up.
  **Operating margin**: Very Negative ~ Very Low - Costs continue to exceed revenue as customer acquisition and R&D spending are still high
  **Reinvestment**: Very High - Heavy spending on scaling operations, hiring, marketing, and infrastructure
  **Sales to Capital Ratio**: Very Low - More capital is required to general a dollar of revenue, as the company builds its operations from scratch`,
    },

    "3. High Growth (The Scaling Up Test)": {
        definition: `💡 **Key Focus**: Expanding market share, increasing efficiency, and leveraging economies of scale.
  
  🟢 **Key Risk**: Business might not scale effectively, leading to stagnation.
  
 **Revenue Growth**: High, slowing slightly - The business gains traction and reaches a wider market.
 **Operating margin**: Negative but improving - Companies still spend heavily on growth, but economies of scale start reducing losses
 **Reinvestment**: High but Stable Relative to Revenue – Spending remains high but becomes more disciplined.
 **Sales to Capital Ratio**: Moderate – Capital efficiency improves as revenue generation strengthens.`,
    },

    "4. Mature Growth (The Midlife Crisis)": {
        definition: `💡 **Key Focus**: Maximising profitability while growing at sustainable pace
  
  🔵 **Key Risk**: No new growth avenues could lead to stagnation.
  
 **Revenue Growth**: Moderate (5 - 15% YoY) - Growth slows as company reaches market saturation.
 **Operating margin**: Positive and increasing - The business has pricing power and economics of scale, improving profitability
 **Reinvestment**: High but Declining - Investment focus on efficiency improvements and expansion into adjacent markets.
**Sales to Capital Ratio**: High – The company becomes more capital-efficient.`,
    },

    "5. Mature Stable Stage (The End Game)": {
        definition: `💡 **Key Focus**: Defending market share and optimising operations.
  
  ⚪ **Key Risk**: Increased competition or market disruption.
  
**Revenue Growth**: Low (<5% YoY) – Growth aligns with inflation or GDP.
**Operating margin**: Very High and Stable – The company dominates its market with strong pricing power.
**Reinvestment**: Low, Focus on Maintenance – The company prioritizes dividends, share buybacks, and acquisitions over expansion.
**Sales to Capital Ratio**: Very High – The company generates significant revenue from existing investments`,
    },

    "6. Decline Stage (The Final Struggle)": {
        definition: `💡 **Key Focus**: Managing decline, cutting costs, or attempting a turnaround.
  
  ❌ **Key Risk**: Irreversible decline leading to bankruptcy or acquisition.
  
**Revenue Growth**: Negative or Close to Zero – Sales decline as demand shrinks or the industry changes.
**Operating margin**: Positive but Declining – Cost-cutting helps maintain profitability initially, but it becomes harder over time.
**Reinvestment**: Variable
    - Companies attempt a turnaround (High Reinvestment) e.g by trying to aggressively reinvest in new product line or acquisitions to revive growth ⇒ high risk
    - Managing Decline (Low Reinvestment, Focus on Cash Extraction), focus on cutting cost, divesting assets and maximise cash flows
**Sales to Capital Ratio**: Variable – If restructuring is successful, efficiency improves; otherwise, inefficiencies increase.`,
    }
};

export const WHEN_TO_SELL = {
    "Better Opportunity Emerges": {
        definition: `When a significantly more attractive investment opportunity presents itself that offers better risk-adjusted returns than your current holding.`
    },

    "Fundamental Deterioration": {
        definition: `When the core business fundamentals or competitive position of the company has significantly weakened.
  
  **Key indicators to monitor:**
  - **Competitive Advantage Erosion**: The company's moats are being eroded by competitors, new technology, or changing consumer preferences
  - **Market Share Loss**: Persistent loss of market share to competitors without a clear recovery plan
  - **Management Quality Decline**: Poor capital allocation decisions, loss of key personnel, or strategic missteps
  - **Industry Headwinds**: Structural changes in the industry that permanently impair the business model`,
    },

    "Position Size Management": {
        definition: `When a single holding becomes too large a percentage of your portfolio, creating concentration risk.
  
  **Guidelines:**
  - Consider trimming when any single position exceeds 20% of your total portfolio
  - Rebalance periodically to maintain proper diversification
  - Don't let winners become so large that they dominate your portfolio risk profile
  - Take some profits from outsized winners to fund new opportunities`,
    },

    "Significant Overvaluation": {
        definition: `When the stock becomes significantly overvalued relative to its intrinsic value, typically by 20% or more.
  
  **Key considerations:**
  - Factor in growth prospects and whether current valuations reflect realistic expectations
  - Remember that markets can remain irrational longer than you expect`,
    },

    "Large Acquisitions (>30% Market Cap)": {
        definition: `When your holding company announces a major acquisition exceeding 30% of its market capitalization.
  
  **Why this matters:**
  - Large deals in fast-growing industries often lead to negative returns, while those in slower-growing sectors might fare better
  - Aswath Damodaran firmly believes that once companies start growing through acquisitions, they cannot stop, and this habit exacts a heavy toll on value creation
  - If you look at the collective evidence across acquisitions, this is the most value-destructive action a company can take (research by KPMG and McKinsey supports this view)
  - **Exception**: Companies excelling in programmatic M&A—focusing on many small deals—tend to outperform, suggesting a strategy of gradual growth can be more effective than large transformational deals`,
    },
};